name: holidays_us
description: Holidays in the United States
homepage: https://github.com/joshpetit/dart_holidays/tree/main/packages/holidays_us
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  date_generator: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
